[build]
  base = "/"  # Set base directory (leave as "/" for root)
  command = "npm run build"  # Adjust based on your framework
  publish = "build"  # Change to "build" if using Create React App

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://www.evens-oven.com/*"
  to = "https://evans-oven.com/:splat"
  status = 301
  force = true

