name: Deploy to Firebase Hosting on PR
on:
  pull_request:
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          # ensure the check runs attach to the PR head commit
          ref: ${{ github.event.pull_request.head.sha }}

      - run: npm ci && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # GITHUB_TOKEN is auto-provisioned; pass it so the action can create the check + PR comment
          repoToken: ${{ github.token }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVANSOVEN }}
          projectId: evansoven
          # optional: expires: 30d
